version: '3'
# Other docker-compose examples in /examples

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --host 0.0.0.0 --trace --config _config.yml,_config-standalone.yml
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
